import { makeChapter } from "./helpers";
import type { Chapter } from "../types";

const dataInterpretation = makeChapter("dilr-di", "dilr", "Data Interpretation", 1, [
  {
    id: "dilr-di-tables",
    title: "Tables",
    description: "Reading structured data tables accurately and fast.",
    difficulty: 2,
    priority: 1,
    estimatedMinutes: 40,
    concept:
      "Table-based DI presents data in rows and columns. The average CAT table question rewards careful reading: check the units of each column, the base year and the direction of change (absolute vs percentage). Develop a habit of marking totals and key rows before answering.",
    coreRules: [
      "Always verify units and period ('in tonnes' vs 'in ₹ crore').",
      "When comparing growth rates, note whether the base differs.",
      "Total row/column is usually the fastest path to 'percentage of overall' answers.",
    ],
    formulas: [],
    examples: [
      {
        title: "Percentage share",
        level: "Easy",
        question: "A table: Region sales 40, 60, 100 (total 200). Percentage of region with 60?",
        solution: ["60/200 = 30%.", "Answer: 30%."],
      },
    ],
    commonMistakes: ["Computing percentage of the wrong total."],
    shortcuts: ["Skim totals first, then answer from the total row."],
    videoId: "dilr-video-di",
    practiceQuestionIds: ["q-dilr-di-table-1"],
  },
  {
    id: "dilr-di-bar",
    title: "Bar Graphs",
    description: "Comparing quantities via bar heights.",
    difficulty: 2,
    priority: 1,
    estimatedMinutes: 35,
    prerequisites: ["dilr-di-tables"],
    concept:
      "Bars encode values by height. Questions ask to compare values, growth between years, or shares. Read the axis scale carefully — a bar double in height does not always mean double the value. The fastest method is reading proportion directly from the graph rather than re-tabulating.",
    coreRules: ["Read the scale before comparing bar heights.", "For growth, always verify which years are adjacent on the axis.", "Stacked bars need careful subtraction to isolate a component."],
    formulas: [],
    examples: [
      {
        title: "Reading scale",
        level: "Easy",
        question: "A bar graph scale: 1 cm = 20 units. A bar of 3 cm represents?",
        solution: ["3 × 20 = 60 units.", "Answer: 60."],
      },
    ],
    commonMistakes: ["Assuming equal heights imply equal values across differing scales."],
    shortcuts: [],
    videoId: "dilr-video-di",
    practiceQuestionIds: [],
  },
  {
    id: "dilr-di-line",
    title: "Line Graphs",
    description: "Trends, slopes and changes over time.",
    difficulty: 2,
    priority: 1,
    estimatedMinutes: 35,
    prerequisites: ["dilr-di-bar"],
    concept:
      "Line graphs show change over time. Slope corresponds to rate of change — a steeper segment means a faster change. Pay attention to whether the axis is linear or starts at a non-zero baseline, which can distort impressions of relative growth.",
    coreRules: ["Slope indicates rate of change, not the value.", "A non-zero baseline exaggerates visual differences.", "Peaks/troughs mark maxima and minima in the period."],
    formulas: [],
    examples: [
      {
        title: "Steepness",
        level: "Easy",
        question: "A line rises steeply 2019-21 then flattens. What changed?",
        solution: ["Growth was rapid in the first window, then nearly zero.", "Answer: high-then-low growth rate."],
      },
    ],
    commonMistakes: ["Reading the steepest line as the largest value."],
    shortcuts: [],
    videoId: "dilr-video-di",
    practiceQuestionIds: [],
  },
  {
    id: "dilr-di-pie",
    title: "Pie Charts",
    description: "Proportions of a whole, central angles and shares.",
    difficulty: 2,
    priority: 1,
    estimatedMinutes: 40,
    prerequisites: ["dilr-di-tables"],
    concept:
      "A pie chart displays each category as a sector of a circle. The central angle is proportional to the share: angle = (share/total) × 360°. Given any two of total, share and angle you can find the third. Comparing two pies requires careful reading of the totals, which often differ.",
    coreRules: ["Angle to share: divide by 360°, not by 100.", "Two pies have different totals — never compare shares directly as values.", "One sector's share can be found from another's angle ratio."],
    formulas: ["Share% = angle/360 × 100"],
    examples: [
      {
        title: "Angle to percent",
        level: "Beginner",
        question: "A sector spans 90°. Its percentage of the whole?",
        solution: ["90/360 = 25%.", "Answer: 25%."],
      },
    ],
    commonMistakes: ["Treating 1° as 1%."],
    shortcuts: ["360°/100 = 3.6° per 1% — convert instantly."],
    videoId: "dilr-video-di",
    practiceQuestionIds: [],
  },
  {
    id: "dilr-di-mixed",
    title: "Mixed Graphs",
    description: "Combinations of charts telling one data story.",
    difficulty: 3,
    priority: 2,
    estimatedMinutes: 40,
    prerequisites: ["dilr-di-table", "dilr-di-line"],
    concept:
      "Mixed charts combine table + line + bar for one dataset. You must switch representations — e.g. revenue from a bar chart, profit% from a line — and join them with arithmetic. The trap is using the wrong chart for the wrong number. Map each chart to its variable before solving.",
    coreRules: ["Identify which chart owns which variable.", "Link across charts via a common variable (e.g. cost = revenue − profit).", "Note axis units of each panel before combining."],
    formulas: [],
    examples: [
      {
        title: "Linking panels",
        level: "Moderate",
        question: "Bar shows revenue; line shows profit% for each of 4 years. Cost in year 2?",
        solution: ["Profit = revenue × profit%/100."],
      },
    ],
    commonMistakes: ["Using profit% as profit in absolute subtraction."],
    shortcuts: [],
    videoId: "dilr-video-di",
    practiceQuestionIds: [],
  },
  {
    id: "dilr-di-caselets",
    title: "Caselets",
    description: "Data wrapped in prose paragraphs.",
    difficulty: 3,
    priority: 1,
    estimatedMinutes: 45,
    prerequisites: ["dilr-di-tables"],
    concept:
      "Caselets hide the table inside sentences. Your first job is to transcribe the data into a mini-table. Standard skills: total/ratio relationships, percentages, and multi-step arithmetic. Missing-data caselets leave a variable to be inferred — define it, write the relations, solve.",
    coreRules: ["Convert prose to a structured table before answering.", "Define unknowns for missing data and write equations.", "Underline every number and its unit while reading."],
    formulas: [],
    examples: [
      {
        title: "Transcribe",
        level: "Moderate",
        question: "'In a school of 600, boys are twice the girls, and each boy read 3 books.' How many books in all?",
        solution: ["Girls = 200, boys = 400.", "400×3 = 1200 books (girls reading not specified).", "Answer: 1200."],
      },
    ],
    commonMistakes: ["Over-assuming data the question does not give."],
    shortcuts: [],
    videoId: "dilr-video-di",
    practiceQuestionIds: [],
  },
  {
    id: "dilr-di-data-comparison",
    title: "Data Comparison",
    description: "Comparing two data sets with ratios and percentages.",
    difficulty: 3,
    priority: 2,
    estimatedMinutes: 40,
    prerequisites: ["dilr-di-tables"],
    concept:
      "Comparison questions pit two datasets against each other — company vs company, year vs year. The core arithmetic: ratio comparison, absolute difference, and percentage change relative to the correct base. Anchor the base year consistently.",
    coreRules: ["Difference percentages need the correct base.", "Ratios simplify before comparison to avoid huge numbers.", "Check whether the question is absolute or percentage in nature."],
    formulas: [],
    examples: [
      {
        title: "Base check",
        level: "Moderate",
        question: "Output rose from 50 to 75. Change is 50% of 50, not of 75.",
        solution: ["Increase = 25; 25/50 = 50%.", "Answer: 50%."],
      },
    ],
    commonMistakes: ["Percentaging against the new value instead of the old."],
    shortcuts: [],
    videoId: "dilr-video-di",
    practiceQuestionIds: [],
  },
  {
    id: "dilr-di-calculation",
    title: "Calculation-Heavy DI",
    description: "Multi-step arithmetic under time pressure.",
    difficulty: 4,
    priority: 1,
    estimatedMinutes: 45,
    prerequisites: ["dilr-di-tables", "qa-arithmetic-percentages"],
    concept:
      "Some DI sets bury the answer under several operations — growth rates over 2 years, weighted combinations, averages of ratios. The strategy is order-of-operations discipline and vibration-free arithmetic: round where rounding is safe, keep fractions intact where it is not. Learn to spot when exact calculation is unavoidable vs when approximation is acceptable.",
    coreRules: ["List the pipeline of steps before picking up the calculator.", "Simplify ratios before multiplying.", "Keep units consistent through every step."],
    formulas: [],
    examples: [
      {
        title: "Two-step",
        level: "Moderate",
        question: "Sales = 200, grew 10% then 20%. Final sales?",
        solution: ["200 × 1.1 × 1.2 = 264.", "Answer: 264."],
      },
    ],
    commonMistakes: ["Adding growth percentages instead of compounding."],
    shortcuts: ["Use the successive-change formula for multi-year growth."],
    videoId: "dilr-video-di",
    practiceQuestionIds: [],
  },
  {
    id: "dilr-di-approximation",
    title: "Approximation and Estimation",
    description: "When to round and when to go precise.",
    difficulty: 3,
    priority: 2,
    estimatedMinutes: 35,
    prerequisites: ["dilr-di-calculation"],
    concept:
      "DI answers are often designed so approximate computation is enough — options sit far apart. Rounding to 2 significant figures and estimating growth earns huge time savings. But first verify the option gap: if the options are close, estimate less aggressively.",
    coreRules: ["Estimate only when the options are far apart.", "Round, then correct the sign of your error at the end.", "Never approximate before checking the base matters."],
    formulas: [],
    examples: [
      {
        title: "Rounded estimate",
        level: "Beginner",
        question: "Options: 49.2, 48.7 vs 14.7. Estimate 1017×0.0482?",
        solution: ["≈ 1000 × 0.048 = 48.", "Answer: 48.x family.", "Exact is ~49.0."],
      },
    ],
    commonMistakes: ["Rounding on the knife-edge of two close options."],
    shortcuts: [],
    videoId: "dilr-video-di",
    practiceQuestionIds: [],
  },
  {
    id: "dilr-di-speed",
    title: "Speed Calculation in DI",
    description: "Doing DI arithmetic mentally and fast.",
    difficulty: 3,
    priority: 1,
    estimatedMinutes: 40,
    prerequisites: ["dilr-di-calculation"],
    concept:
      "Speed in DI is a game of habits: memorized conversions (1/8 = 12.5%, 1/7 ≈ 14.3%), deviations-from-base addition, and algebraic pre-simplification. Multiply 2-digit numbers with the base-100 trick; divide by cancelling factors. Every 10 seconds saved per question compresses a DILR set by minutes.",
    coreRules: ["Memorize fraction→percent table (1/2 … 1/20).", "Simplify before you compute.", "Practice mental squaring and doubling tables."],
    formulas: [],
    examples: [
      {
        title: "Base-100 shortcut",
        level: "Easy",
        question: "98 × 96 mentally?",
        solution: [
          "100 − 2 and 100 − 4.",
          "Product = (100−2−4)×100 + 2×4 = 9408.",
          "Answer: 9408.",
        ],
      },
    ],
    commonMistakes: ["Rushing accuracy away in speed drills."],
    shortcuts: ["The 100-base multiplication trick is the highest-yield mental-math shortcut."],
    videoId: "dilr-video-di",
    practiceQuestionIds: [],
  },
]);

const logicalReasoning = makeChapter("dilr-lr", "dilr", "Logical Reasoning", 2, [
  {
    id: "dilr-lr-linear",
    title: "Linear Arrangements",
    description: "Arranging entities in a single line with constraints.",
    difficulty: 2,
    priority: 1,
    estimatedMinutes: 45,
    concept:
      "Linear arrangement places people/objects in a left-to-right order. Extracting every constraint into a sketch is the whole technique: mark ends, note neighbours ('A is next to B'), and use 'to the left of'/'between' relations as you fill slots. When a clue is ambiguous, branch the possibilities.",
    coreRules: ["Sketch a slot row first and fill it as clues confirm.", "'Between' means exactly 2 neighbours flank it.", "Ambiguous clues → try both branches; discard contradictions."],
    formulas: [],
    examples: [
      {
        title: "Sketching",
        level: "Moderate",
        question: "Five in a row: A to the immediate left of B, C at an end, D between B and E. Fixed position of A?",
        solution: [
          "C at an end: slot 1 or 5.",
          "Test: C=1 → A,B adjacent later, D between B,E. Arrangement C,A,B,D,E (A=2).",
          "C=5 is impossible (needs D between B and E to its left) → A is 2nd.",
        ],
      },
    ],
    commonMistakes: ["Skipping the sketch and reasoning verbally — the #1 cause of LR errors."],
    shortcuts: ["Write constraints as shorthand arrows (immediate / somewhere-left)."],
    videoId: "dilr-video-lr",
    practiceQuestionIds: [],
  },
  {
    id: "dilr-lr-circular",
    title: "Circular Arrangements",
    description: "Arrangements around a circle; facing directions.",
    difficulty: 3,
    priority: 1,
    estimatedMinutes: 50,
    prerequisites: ["dilr-lr-linear"],
    concept:
      "People sit around a table, sometimes facing in or out. Facing in: left and right are mirror-reversed from an external view ('someone's right' becomes the person on your left when viewed from outside). Fix a reference point first (rarely given — place the first certain person arbitrarily), then walk the circle.",
    coreRules: ["Fix one known position before branching.", "Mirror left/right when 'facing inside' is declared.", "Adjacent = immediate neighbour; opposite = across."],
    formulas: [],
    examples: [
      {
        title: "Facing-in reversal",
        level: "Moderate",
        question: "Six face a table. 'B is third to the right of A.' When facing in, is that drawing direction clockwise?",
        solution: ["For a table-face-in viewer, their right is your diagram's left, so the physical direction reverses.", "Answer: draw B at A's left-clockwise offset by 3 slots."],
      },
    ],
    commonMistakes: ["Forgetting the face-direction reversal — the classic circular trap."],
    shortcuts: ["Draw arrows showing face direction, then treat the circle as a labelled clock."],
    videoId: "dilr-video-lr",
    practiceQuestionIds: [],
  },
  {
    id: "dilr-lr-seating",
    title: "Seating Arrangements",
    description: "Complex mixed seating with multiple clues.",
    difficulty: 3,
    priority: 1,
    estimatedMinutes: 50,
    prerequisites: ["dilr-lr-circular", "dilr-lr-linear"],
    concept:
      "Seating problems mix rows, circles, facing-different-directions and conditional ties. The structured approach never changes: translate every clue to a symbol, place the strongest constraint first, branch when needed, and stop the moment two branches corroborate the asked value.",
    coreRules: ["Rank clues by determinacy before solving.", "Use the 'one person at once' fill order.", "Contradictions prune branches; never abandon a branch too early."],
    formulas: [],
    examples: [],
    commonMistakes: [],
    shortcuts: [],
    videoId: "dilr-video-lr",
    practiceQuestionIds: [],
  },
  {
    id: "dilr-lr-distribution",
    title: "Distribution",
    description: "Allocating items/people to groups or slots.",
    difficulty: 3,
    priority: 1,
    estimatedMinutes: 45,
    concept:
      "Distribution assigns things to categories (colors, cities, companies). Treat each entity as a placeholder with one-to-one mapping. The power move is combining constraints into 'if X is in slot 2 then…' chains and using the exclusivity of categories to eliminate.",
    coreRules: ["One-to-one → each slot takes one entity; use that for deduction.", "Exclusive rules ('only engineers in Chennai') compress choices quickly.", "Case-split on the least-constrained variable."],
    formulas: [],
    examples: [
      {
        title: "Mapping",
        level: "Easy",
        question: "3 people, 3 cities, each in one. 'R in Delhi, S not in Pune' → who is in Pune?",
        solution: ["R=Delhi. T must be in Pune if S isn't (only 2 cities left).", "Answer: T."],
      },
    ],
    commonMistakes: ["Double-using a constraint to force a wrong assignment."],
    shortcuts: [],
    videoId: "dilr-video-lr",
    practiceQuestionIds: [],
  },
  {
    id: "dilr-lr-selection",
    title: "Selection / Team Formation",
    description: "Choosing subsets subject to constraints.",
    difficulty: 3,
    priority: 1,
    estimatedMinutes: 45,
    prerequisites: ["qa-mod-combinations"],
    concept:
      "Selection problems choose a team of k from n with conditions ('exactly one of X and Y', 'if A then not B'). Translate each rule to logic: at-most-one, at-least-one, conditional. The questions ask who must/may be in the team — evaluate possible combinations exhaustively but efficiently.",
    coreRules: ["Convert every condition to a logical shorthand.", "At-most-one pairs narrow strongly.", "When asked 'who must be in', prove it: absence must cause contradiction."],
    formulas: [],
    examples: [
      {
        title: "At-most-one",
        level: "Moderate",
        question: "Pick 3 of {A,B,C,D,E} with at most one of A,B; if C then D. Which must be picked?",
        solution: [
          "Try leaving D out → C must be out → pick 3 from A,B,E → violates at-most-one (A,B both in).",
          "So D must be in.",
          "Answer: D.",
        ],
      },
    ],
    commonMistakes: ["Forgetting the contrapositive of a conditional clue."],
    shortcuts: ["The 'if not D then contradiction' proof is the canonical must-in technique."],
    videoId: "dilr-video-lr",
    practiceQuestionIds: [],
  },
  {
    id: "dilr-lr-grouping",
    title: "Grouping",
    description: "Partitioning a set into teams with boundary rules.",
    difficulty: 3,
    priority: 2,
    estimatedMinutes: 45,
    prerequisites: ["dilr-lr-selection"],
    concept:
      "Grouping partitions all n members into m groups, possibly with size limits and pairwise prohibitions. The skeleton is a grid (member × group). Fill with certainty, branch at ambiguity, and use total-size constraints as a global check.",
    coreRules: ["Respect total capacity across groups.", "Pair-prohibitions eliminate across both groups at once.", "Keep the grid neat — the answer falls out of completed rows/columns."],
    formulas: [],
    examples: [],
    commonMistakes: [],
    shortcuts: [],
    videoId: "dilr-video-lr",
    practiceQuestionIds: [],
  },
  {
    id: "dilr-lr-scheduling",
    title: "Scheduling",
    description: "Ordering events across days, slots and weeks.",
    difficulty: 3,
    priority: 1,
    estimatedMinutes: 45,
    prerequisites: ["dilr-lr-linear"],
    concept:
      "Schedule problems order events over a calendar: each day gets one event, each event once, plus relative rules ('exam on days 2-4' or 'two days apart'). Build a day-grid and fill like a linear arrangement with dates. Watch twists like 'no two consecutive' — which force alternating patterns.",
    coreRules: ["Map events to the timeline before clues.", "'No two consecutive' often forces a fixed alternating skeleton.", "Adjacent/authored gaps are the strongest fillers."],
    formulas: [],
    examples: [
      {
        title: "Consecutive-block",
        level: "Moderate",
        question: "6 lectures on 6 days; the two maths lectures are not on consecutive days. Patterns?",
        solution: ["The non-consecutive pair splits the week; place strongest fixed item first.", "Fill combinations that satisfy the split."],
      },
    ],
    commonMistakes: ["Losing track of which events remain unplaced."],
    shortcuts: [],
    videoId: "dilr-video-lr",
    practiceQuestionIds: [],
  },
  {
    id: "dilr-lr-tournaments",
    title: "Games and Tournaments",
    description: "Knockouts, round-robins, wins and netting from results.",
    difficulty: 4,
    priority: 2,
    estimatedMinutes: 50,
    prerequisites: ["dilr-lr-selection"],
    concept:
      "Tournament logic codifies match outcomes. For a round-robin of n players: total matches = nC2; each match yields win/loss (or draw). Points are configured (2 for a win etc.), and the asked quantity is deducible from a point/tally table. Knockouts: n−1 matches for n entrants. Convert every spoken condition into a tally row.",
    coreRules: ["Round-robin: nC2 matches; sum of wins = sum of losses (no draws) or accounted draws.", "Knockout: champion needs n−1 wins.", "Rebalance points after each result — track running tallies."],
    formulas: ["Matches (league) = nC2", "Knockout games = n − 1"],
    examples: [
      {
        title: "League tally",
        level: "Moderate",
        question: "4 teams round-robin, 2 pts per win, 1 for draw, 0 loss. Table: A 5 pts after 3 games. Possible W/D/L?",
        solution: ["2W+1D = 5 → A has 2 wins, 1 draw, 0 losses.", "Answer: 2-0-1."],
      },
    ],
    commonMistakes: ["Forgetting draws consume a point each."],
    shortcuts: [],
    videoId: "dilr-video-lr",
    practiceQuestionIds: [],
  },
  {
    id: "dilr-lr-rankings",
    title: "Rankings and Ordering",
    description: "Relative ranks across categories.",
    difficulty: 2,
    priority: 2,
    estimatedMinutes: 40,
    prerequisites: ["dilr-lr-linear"],
    concept:
      "Ranking gives order positions, possibly in more than one category ('third in running, fifth in swimming'). The typical device is a rank-matrix and questions about max/min possible positions. Combine the constraints by bounding each individual's range.",
    coreRules: ["Convert 'better/worse' to numeric ranks.", "Bounding: min possible rank from the worst single placement.", "No two same rank in one category unless stated."],
    formulas: [],
    examples: [
      {
        title: "Bounding",
        level: "Easy",
        question: "A is worse than 4 in sports and better than 3 in academics (10 total each). Max possible overall?",
        solution: ["Sports rank ≥ 5; academics ≤ 7.", "Answer: still bounded by the two category ranks."],
      },
    ],
    commonMistakes: ["Assuming rankings transfer between categories."],
    shortcuts: [],
    videoId: "dilr-video-lr",
    practiceQuestionIds: [],
  },
  {
    id: "dilr-lr-blood-relations",
    title: "Blood Relations",
    description: "Decoding family networks from relation statements.",
    difficulty: 2,
    priority: 1,
    estimatedMinutes: 40,
    concept:
      "Blood-relation questions encode a family tree in prose or symbols. Draw a compact tree with unambiguous gender symbols and generations, then trace each relation. Danger points: in-laws, cousins vs siblings, and gender assumptions (only assign gender when stated or logically forced).",
    coreRules: ["Assign gender only when forced.", "Draw generations top-down; marriage links side-by-side.", "Check each parent linkage before answering."],
    formulas: [],
    examples: [
      {
        title: "Tree",
        level: "Easy",
        question: "P is the father of Q, Q is the mother of R. P's relation to R?",
        solution: ["R is 3rd generation; P is male, two steps up through Q.", "Answer: maternal grandfather."],
      },
    ],
    commonMistakes: ["Assuming a spouse's gender or a missing parent."],
    shortcuts: [],
    videoId: "dilr-video-lr",
    practiceQuestionIds: [],
  },
  {
    id: "dilr-lr-networks-routes",
    title: "Networks and Routes",
    description: "Paths, shortest connections and reachability.",
    difficulty: 3,
    priority: 2,
    estimatedMinutes: 40,
    concept:
      "Network questions map cities/rooms with connection lines. The core needs: adjacency, path-existence, shortest distance, and cut-points (a city whose removal disconnects the map). Draw clean, and mark distances on edges. Shortest route = scan candidate paths, not all paths.",
    coreRules: ["Shortest distance needs careful candidate comparison.", "A cut node is a node on every route between two others.", "Draw distance labels on edges to avoid re-reading text."],
    formulas: [],
    examples: [
      {
        title: "Shortest path",
        level: "Easy",
        question: "A→B via C is 5+7=12; via D is 4+6=10. Shortest?",
        solution: ["Candidate compare: 10 < 12.", "Answer: via D, 10."],
      },
    ],
    commonMistakes: ["Picking the first found path without comparing."],
    shortcuts: [],
    videoId: "dilr-video-lr",
    practiceQuestionIds: [],
  },
  {
    id: "dilr-lr-binary",
    title: "Binary Logic",
    description: "Truth-tellers, liars and conditional speakers.",
    difficulty: 4,
    priority: 2,
    estimatedMinutes: 45,
    prerequisites: ["dilr-lr-selection"],
    concept:
      "People who always tell truth / always lie / alternate, respond to questions. The technique is case-analysis: hypothesize a speaker as truth-teller, propagate, and discard contradictions. Statements of the form 'I am a liar' are self-referential — handle with the liar paradox carefully.",
    coreRules: ["Truth-tellers never utter false statements.", "Liars never utter true statements.", "Contradiction prunes a hypothesis."],
    formulas: [],
    examples: [
      {
        title: "Truth table",
        level: "Moderate",
        question: "A says 'B lies'; B says 'A tells truth'. Who lies?",
        solution: [
          "If A truthful → B lies → B is a liar who states truth? Contradiction.",
          "If A liar → B truthful, consistent with B's statement about A being... check.",
          "Answer: consistent model A liar, B truthful.",
        ],
      },
    ],
    commonMistakes: ["Ignoring self-referential traps."],
    shortcuts: [],
    videoId: "dilr-video-lr",
    practiceQuestionIds: [],
  },
  {
    id: "dilr-lr-conditional",
    title: "Conditional Logic",
    description: "'If-then' constraints and their contrapositives.",
    difficulty: 3,
    priority: 1,
    estimatedMinutes: 40,
    prerequisites: ["dilr-lr-selection"],
    concept:
      "Conditional constraints ('if X plays, Y doesn't') have exact logical force: X → not Y, equivalent to Y → not X. Never reverse incorrectly. Chain conditionals to derive new rules, and use contrapositives to unlock 'who must not' style questions.",
    coreRules: ["A→B equals not-B→not-A (contrapositive).", "A→B does NOT equal B→A.", "Combining A→B and B→C gives A→C."],
    formulas: [],
    examples: [
      {
        title: "Contrapositive",
        level: "Easy",
        question: "If it rains, the match is cancelled. Match not cancelled ⇒ ?",
        solution: ["Contrapositive: not cancelled → not rained.", "Answer: it didn't rain."],
      },
    ],
    commonMistakes: ["Reversing the conditional."],
    shortcuts: [],
    videoId: "dilr-video-lr",
    practiceQuestionIds: [],
  },
  {
    id: "dilr-lr-matrix",
    title: "Matrix Problems",
    description: "2D grids and cross-tabulations.",
    difficulty: 3,
    priority: 2,
    estimatedMinutes: 40,
    concept:
      "Matrix problems tabulate two attributes (e.g. sport × department) with occupancy and max-count clues. Solve by ticking/crossing cells. The power of the grid format: an X in one cell forces complements along its row/column.",
    coreRules: ["Complete one row/column at a time.", "A filled cell eliminates its row and column options.", "Anchor with the strongest explicit match first."],
    formulas: [],
    examples: [
      {
        title: "Grid deduction",
        level: "Easy",
        question: "2 sports, 2 people, each plays one but different. If A plays Cricket…",
        solution: ["B must play the other sport.", "Answer: B = the non-cricket sport."],
      },
    ],
    commonMistakes: ["Filling the same sport twice."],
    shortcuts: [],
    videoId: "dilr-video-lr",
    practiceQuestionIds: [],
  },
  {
    id: "dilr-lr-set-lr",
    title: "Set-Based LR",
    description: "LR problems organized as a single complex set.",
    difficulty: 4,
    priority: 1,
    estimatedMinutes: 50,
    prerequisites: ["dilr-lr-seating", "dilr-lr-scheduling"],
    concept:
      "Modern CAT LR arrives as one big scenario with 4 questions, mixing arrangements + conditions + numeric relations. The discipline: read the whole scenario, build the master grid, fill what is certain, and branch only where a question's extra data can disambiguate. The first question usually establishes the structure.",
    coreRules: ["Master grid first, question-labels after.", "Each question's novel condition may fill a fresh gap — use it locally.", "Answers must be consistent across all questions (same base setup)."],
    formulas: [],
    examples: [],
    commonMistakes: ["Treating each question as an independent puzzle."],
    shortcuts: [],
    videoId: "dilr-video-lr",
    practiceQuestionIds: [],
  },
  {
    id: "dilr-lr-quant-lr",
    title: "Quant-Based LR",
    description: "LR fused with arithmetic data (scores, ages, budgets).",
    difficulty: 4,
    priority: 1,
    estimatedMinutes: 50,
    prerequisites: ["dilr-lr-set-lr", "qa-arithmetic-averages"],
    concept:
      "These sets inject numbers into arrangements: scores summing to known totals, ages in ratio, prices in arithmetic relations. Translate each numeric condition into an equation alongside the grid; solve the equation system where the grid stalls. The arithmetic is usually simple — the difficulty is joining both languages fluently.",
    coreRules: ["Write the numeric relations as equations beside the grid.", "Sums/averages convert to total constraints.", "Solve the clean equations first, then feed results to the grid."],
    formulas: [],
    examples: [
      {
        title: "Cross-language",
        level: "Moderate",
        question: "Three students' scores sum to 240 with pairwise differences of 10. Grids assign topics; equations give scores.",
        solution: ["Solve x+(x+10)+(x+20)=240 → x=70.", "Feed 70/80/90 into the assignment grid."],
      },
    ],
    commonMistakes: ["Forgetting to port the solved numbers back into the arrangement."],
    shortcuts: [],
    videoId: "dilr-video-lr",
    practiceQuestionIds: [],
  },
  {
    id: "dilr-lr-hybrid",
    title: "Hybrid DILR",
    description: "Merging DI data with reasoning structure.",
    difficulty: 4,
    priority: 1,
    estimatedMinutes: 55,
    prerequisites: ["dilr-di-caselets", "dilr-lr-quant-lr"],
    concept:
      "Hybrid sets present a table/chart alongside logical constraints ('exactly one of the top 2 companies is from Delhi'). Strategy: read the data, extract the constraints as relation-flags, and let the grid + arithmetic reinforce each other. Hybrids reward organized dual-tracking more than speed.",
    coreRules: ["Track data and constraints in separate but linked registers.", "Delete data cells a constraint makes impossible.", "Verify final answers against both the chart and the constraints."],
    formulas: [],
    examples: [],
    commonMistakes: ["Splitting focus — flip-flopping between chart and clues."],
    shortcuts: [],
    videoId: "dilr-video-lr",
    practiceQuestionIds: [],
  },
]);

import type { Chapter as DChapter } from "../types";
export const DILR_CHAPTERS: DChapter[] = [dataInterpretation, logicalReasoning];