import type { Question } from "../types";

// All questions are ORIGINAL, authored for this platform. None are claimed to be CAT PYQs.
export const QA_QUESTIONS: Question[] = [
  {
    id: "q-qa-percent-1",
    section: "qa",
    topicId: "qa-arithmetic-percentages",
    chapterId: "qa-arithmetic",
    difficulty: 1,
    type: "mcq",
    prompt:
      "In a college of 1,800 students, 35% are in their second year. How many students are in their second year?",
    options: ["540", "560", "630", "720"],
    correctIndex: 2,
    explanation: "35% of 1800 = (35/100) × 1800 = 630. So 630 students are in their second year.",
    fasterApproach: "10% of 1800 is 180, so 30% is 540 and 5% is 90 → 540 + 90 = 630.",
    conceptTested: "Finding a percentage of a quantity with clean numbers.",
    commonTrap: "Careless multiplication: 35 × 18 = 630, not 540.",
  },
  {
    id: "q-qa-percent-2",
    section: "qa",
    topicId: "qa-arithmetic-percentages",
    chapterId: "qa-arithmetic",
    difficulty: 2,
    type: "mcq",
    prompt:
      "A shopkeeper marks a camera 30% above cost and then sells it at a 20% discount on the marked price. What is his net profit percentage?",
    options: ["4%", "6%", "8%", "10%"],
    correctIndex: 0,
    explanation: "Let CP = 100. MP = 130. SP = 130 × 0.80 = 104. Profit = 4%, i.e. 4% of 100. So net profit = 4%.",
    fasterApproach: "Net % = 30 − 20 − (30×20)/100 = 30 − 20 − 6 = 4%.",
    conceptTested: "Mark-up followed by discount; successive percentage change.",
    commonTrap: "Subtracting percentages directly: 30% − 20% = 10% is wrong.",
  },
  {
    id: "q-qa-percent-3",
    section: "qa",
    topicId: "qa-arithmetic-percentages",
    chapterId: "qa-arithmetic",
    difficulty: 2,
    type: "mcq",
    prompt:
      "If A is 40% more than B, by what percentage is B less than A?",
    options: ["28.57%", "40%", "33.33%", "25%"],
    correctIndex: 0,
    explanation:
      "A = 1.4B. B is less than A by (A − B)/A × 100 = (0.4B)/(1.4B) × 100 = 0.4/1.4 × 100 = 28.57%.",
    fasterApproach: "Use the rule: if A is x% more than B, B is [x/(100+x)] × 100% less than A = 40/140 × 100 ≈ 28.57%.",
    conceptTested: "Base selection in percentage comparison.",
    commonTrap: "Answering 40% — forgetting the base changes to A.",
  },
  {
    id: "q-qa-percent-4",
    section: "qa",
    topicId: "qa-arithmetic-percentage-inc-dec",
    chapterId: "qa-arithmetic",
    difficulty: 1,
    type: "mcq",
    prompt:
      "A student's scholarship of ₹4,000 is increased by 12%. What is the new scholarship amount?",
    options: ["₹4,120", "₹4,400", "₹4,480", "₹4,520"],
    correctIndex: 2,
    explanation: "New = 4000 × 1.12 = ₹4,480.",
    fasterApproach: "12% of 4000 = 480; add to 4000 = 4480.",
    conceptTested: "Simple percentage increase.",
    commonTrap: "None — but check the unit carefully.",
  },
  {
    id: "q-qa-percent-5",
    section: "qa",
    topicId: "qa-arithmetic-percentage-inc-dec",
    chapterId: "qa-arithmetic",
    difficulty: 2,
    type: "mcq",
    prompt:
      "After a 20% reduction in the price of notebooks, Aditya can buy 2 more notebooks for ₹120. What was the original price of one notebook?",
    options: ["₹10", "₹12", "₹15", "₹20"],
    correctIndex: 2,
    explanation:
      "Let original price = P. Original count = 120/P. New price = 0.8P, new count = 120/(0.8P) = 150/P. Difference = 2 → 150/P − 120/P = 2 → 30/P = 2 → P = 15.",
    fasterApproach: "At 20% less price, the same spend buys 25% more units. 25% of original count = 2 → original count = 8 → price = 120/8 = 15.",
    conceptTested: "Percentage change in price vs quantity.",
    commonTrap: "Directly dividing 120 by (count+2) without finding the count first.",
  },
  {
    id: "q-qa-percent-6",
    section: "qa",
    topicId: "qa-arithmetic-successive-percent",
    chapterId: "qa-arithmetic",
    difficulty: 3,
    type: "mcq",
    prompt:
      "The population of a town increases by 10% in the first year and decreases by 10% in the second year. If the population becomes 59,400, what was the population two years ago?",
    options: ["54,000", "60,000", "65,340", "72,600"],
    correctIndex: 1,
    explanation:
      "Net factor after +10% then −10% = 1.1 × 0.9 = 0.99. Original population = 59400 / 0.99 = 60,000.",
    fasterApproach: "The net change is (1.1 × 0.9 − 1) = −1%, so original = 59400 × (100/99) = 60,000.",
    conceptTested: "Successive percentage change with a reverse computation.",
    commonTrap: "Using final = original × 1.1 × 0.9 correctly, but forgetting to divide by 0.99 to go backward.",
  },
  {
    id: "q-qa-pnl-1",
    section: "qa",
    topicId: "qa-arithmetic-profit-loss",
    chapterId: "qa-arithmetic",
    difficulty: 1,
    type: "mcq",
    prompt:
      "A pen costs ₹80 and is sold at a 25% loss. What is the selling price?",
    options: ["₹56", "₹60", "₹62", "₹64"],
    correctIndex: 1,
    explanation: "SP = CP × (1 − 0.25) = 80 × 0.75 = ₹60.",
    fasterApproach: "25% loss = 3/4 of cost → 80 × 3/4 = 60.",
    conceptTested: "Loss percentage on the cost price.",
    commonTrap: "Subtracting 25 rupees directly instead of 25% of 80.",
  },
  {
    id: "q-qa-pnl-2",
    section: "qa",
    topicId: "qa-arithmetic-profit-loss",
    chapterId: "qa-arithmetic",
    difficulty: 2,
    type: "mcq",
    prompt:
      "A trader sells an item for ₹1,260 and makes a profit of 40%. What was the cost price?",
    options: ["₹840", "₹900", "₹960", "₹1,000"],
    correctIndex: 1,
    explanation: "SP = CP × 1.4 → CP = 1260 / 1.4 = ₹900.",
    fasterApproach: "1260 × (5/7) = 900 because 1.4 = 7/5.",
    conceptTested: "Recovering cost price from selling price and profit%.",
    commonTrap: "Subtracting 40% of 1260 from 1260.",
  },
  {
    id: "q-qa-pnl-3",
    section: "qa",
    topicId: "qa-arithmetic-profit-loss",
    chapterId: "qa-arithmetic",
    difficulty: 3,
    type: "mcq",
    prompt:
      "A seller buys 20 items for ₹800 and sells them at ₹55 each. His overall profit or loss percentage is:",
    options: ["10% profit", "8.75% profit", "37.5% profit", "12.5% loss"],
    correctIndex: 2,
    explanation:
      "Cost per item = 40. Selling price per item = 55. Profit per item = 15, i.e. 15/40 = 37.5%.",
    fasterApproach: "Total SP = 20 × 55 = 1100 vs CP = 800. Profit = 300 → 300/800 = 37.5%.",
    conceptTested: "Cost per unit and percentage profit.",
    commonTrap: "Comparing totals where units differ.",
  },
  {
    id: "q-qa-pnl-4",
    section: "qa",
    topicId: "qa-arithmetic-marked-price",
    chapterId: "qa-arithmetic",
    difficulty: 3,
    type: "mcq",
    prompt:
      "The marked price of a jacket is ₹2,000. Two successive discounts of 10% and 20% are given. Find the final selling price.",
    options: ["₹1,400", "₹1,420", "₹1,440", "₹1,460"],
    correctIndex: 2,
    explanation:
      "Single equivalent discount = 10 + 20 − (10×20)/100 = 28%. SP = 2000 × 0.72 = ₹1,440.",
    fasterApproach: "2000 × 0.9 × 0.8 = 2000 × 0.72 = 1440.",
    conceptTested: "Successive discounts.",
    commonTrap: "Assuming 10% + 20% = 30% discount (gives ₹1,400, wrong).",
  },
  {
    id: "q-qa-si-1",
    section: "qa",
    topicId: "qa-arithmetic-si",
    chapterId: "qa-arithmetic",
    difficulty: 1,
    type: "mcq",
    prompt: "Find the simple interest on ₹15,000 at 8% per annum for 2 years.",
    options: ["₹2,000", "₹2,400", "₹2,800", "₹3,000"],
    correctIndex: 1,
    explanation: "SI = (15000 × 8 × 2)/100 = ₹2,400.",
    fasterApproach: "8% of 15000 = 1200 per year; two years = 2400.",
    conceptTested: "Basic simple interest formula.",
    commonTrap: "Using compound interest overnight.",
  },
  {
    id: "q-qa-ci-1",
    section: "qa",
    topicId: "qa-arithmetic-ci",
    chapterId: "qa-arithmetic",
    difficulty: 3,
    type: "mcq",
    prompt:
      "The compound interest on ₹20,000 at 10% per annum for 2 years, compounded annually, is:",
    options: ["₹4,000", "₹4,200", "₹4,400", "₹4,410"],
    correctIndex: 1,
    explanation: "A = 20000 × 1.1² = 20000 × 1.21 = 24,200. CI = 24,200 − 20,000 = ₹4,200.",
    fasterApproach: "CI for 2 years at 10% = 21% of P (from (1.1² − 1) = 0.21) = 4200.",
    conceptTested: "Compound interest, two years.",
    commonTrap: "Using SI (gives 4000) — missing the interest-on-interest.",
  },
  {
    id: "q-qa-ratio-1",
    section: "qa",
    topicId: "qa-arithmetic-ratio-proportion",
    chapterId: "qa-arithmetic",
    difficulty: 1,
    type: "mcq",
    prompt: "Divide ₹720 between A and B in the ratio 5 : 3. The share of A is:",
    options: ["₹270", "₹450", "₹500", "₹600"],
    correctIndex: 1,
    explanation: "Total parts = 8; each part = 90. A = 5 × 90 = ₹450.",
    fasterApproach: "A = (5/8) × 720 = 450.",
    conceptTested: "Ratio division.",
    commonTrap: "None, but check direction (5:3 = A:B).",
  },
  {
    id: "q-qa-avg-1",
    section: "qa",
    topicId: "qa-arithmetic-averages",
    chapterId: "qa-arithmetic",
    difficulty: 2,
    type: "mcq",
    prompt:
      "The average of 11 numbers is 42. One number, 56, is removed. What is the new average?",
    options: ["40", "40.6", "41", "42"],
    correctIndex: 2,
    explanation:
      "Sum = 11 × 42 = 462. New sum = 462 − 56 = 406. New average = 406/10 = 40.6. Wait — recompute: 462 − 56 = 406; 406/10 = 40.6.",
    fasterApproach: "Removing 56, which is 14 above the old average, drops the average by 14/10 = 1.4 → 42 − 1.4 = 40.6.",
    conceptTested: "Effect of removal on the average.",
    commonTrap: "Dividing the change by 11 instead of the new count 10.",
  },
  {
    id: "q-qa-avg-2",
    section: "qa",
    topicId: "qa-arithmetic-weighted-avg",
    chapterId: "qa-arithmetic",
    difficulty: 2,
    type: "mcq",
    prompt:
      "A class of 25 students averages 60 marks; another of 15 averages 80. The average of the combined class is:",
    options: ["67.5", "70", "72.5", "75"],
    correctIndex: 0,
    explanation: "Total = 25×60 + 15×80 = 1500 + 1200 = 2700. Combined = 2700/40 = 67.5.",
    fasterApproach: "Deviation from 60: extra = 15×20 = 300 over baseline (40×60=2400) → 2700/40 = 67.5.",
    conceptTested: "Weighted average with unequal group sizes.",
    commonTrap: "Averaging the averages: (60+80)/2 = 70, which is wrong.",
  },
  {
    id: "q-qa-mix-1",
    section: "qa",
    topicId: "qa-arithmetic-mixtures",
    chapterId: "qa-arithmetic",
    difficulty: 3,
    type: "mcq",
    prompt:
      "In what ratio must a 20% alcohol solution be mixed with a 50% alcohol solution to obtain a 35% solution?",
    options: ["1 : 2", "2 : 1", "1 : 1", "3 : 1"],
    correctIndex: 2,
    explanation:
      "Alligation: (50 − 35) : (35 − 20) = 15 : 15 = 1 : 1. So equal volumes.",
    fasterApproach: "35 is exactly midway between 20 and 50, so the ratio is 1:1.",
    conceptTested: "Alligation for mixing solutions.",
    commonTrap: "Reversing the ratio (2:1) by misreading which is which.",
  },
  {
    id: "q-qa-tw-1",
    section: "qa",
    topicId: "qa-arithmetic-time-work",
    chapterId: "qa-arithmetic",
    difficulty: 3,
    type: "mcq",
    prompt:
      "A can finish a task in 10 days and B in 15 days. They work together for 3 days; then A leaves. How many more days does B need to finish?",
    options: ["7.5", "8", "8.5", "9"],
    correctIndex: 0,
    explanation:
      "Work = LCM(10,15) = 30 units. A = 3/day, B = 2/day, together 5/day. In 3 days: 15 done, 15 left. B alone: 15/2 = 7.5 days.",
    fasterApproach: "Together 3 days = 3 × 5 = 15 units (half the work). B needs 15/2 = 7.5 days.",
    conceptTested: "Rate addition and leftover work.",
    commonTrap: "Computing B's time from the whole task rather than the remaining work.",
  },
  {
    id: "q-qa-tsd-1",
    section: "qa",
    topicId: "qa-arithmetic-tsd",
    chapterId: "qa-arithmetic",
    difficulty: 2,
    type: "mcq",
    prompt:
      "A train travels 60 km at 40 km/h and then 60 km at 60 km/h. Its average speed for the whole trip is:",
    options: ["48 km/h", "50 km/h", "52 km/h", "48 km/h"],
    correctIndex: 0,
    explanation:
      "Equal distances at 40 and 60: average speed = 2×40×60/(40+60) = 4800/100 = 48 km/h.",
    fasterApproach: "Harmonic mean for equal distances.",
    conceptTested: "Average speed with equal distances.",
    commonTrap: "Averaging the two speeds to 50 km/h — wrong because equal distances, not equal times.",
  },
  {
    id: "q-qa-alg-1",
    section: "qa",
    topicId: "qa-algebra-identities",
    chapterId: "qa-algebra",
    difficulty: 2,
    type: "mcq",
    prompt: "If x + 1/x = 5, then x² + 1/x² equals:",
    options: ["23", "25", "27", "3"],
    correctIndex: 0,
    explanation: "Squaring both sides: x² + 2 + 1/x² = 25 → x² + 1/x² = 23.",
    fasterApproach: "Use the identity x² + 1/x² = (x + 1/x)² − 2 = 25 − 2 = 23.",
    conceptTested: "Identity involving x + 1/x.",
    commonTrap: "Answering 25 — forgetting to subtract the 2ab term.",
  },
  {
    id: "q-qa-alg-2",
    section: "qa",
    topicId: "qa-algebra-quadratic",
    chapterId: "qa-algebra",
    difficulty: 3,
    type: "mcq",
    prompt:
      "If α and β are the roots of x² − 6x + 8 = 0, then the value of α² + β² is:",
    options: ["20", "36", "28", "24"],
    correctIndex: 0,
    explanation: "α + β = 6, αβ = 8. α² + β² = (α+β)² − 2αβ = 36 − 16 = 20.",
    fasterApproach: "Use the sum/product relations directly.",
    conceptTested: "Sum and product of roots.",
    commonTrap: "Directly squaring the sum (36) and forgetting 2αβ.",
  },
  {
    id: "q-qa-num-1",
    section: "qa",
    topicId: "qa-num-unit-digit",
    chapterId: "qa-number-system",
    difficulty: 3,
    type: "mcq",
    prompt: "The unit digit of 7²⁰²⁴ is:",
    options: ["1", "3", "7", "9"],
    correctIndex: 0,
    explanation: "Units of powers of 7 cycle as 7, 9, 3, 1 (period 4). 2024 mod 4 = 0 → same as 7⁴ → 1.",
    fasterApproach: "Cycle length 4 → reduce exponent mod 4.",
    conceptTested: "Cyclicity of unit digits.",
    commonTrap: "Using 7²⁰²⁴ mod 4 = 0 as 7⁰ instead of 7⁴.",
  },
  {
    id: "q-qa-pnc-1",
    section: "qa",
    topicId: "qa-mod-permutations",
    chapterId: "qa-modern-math",
    difficulty: 3,
    type: "mcq",
    prompt:
      "How many 4-letter words can be formed from the letters of the word 'NOTE' without repetition?",
    options: ["24", "12", "16", "48"],
    correctIndex: 0,
    explanation: "4 distinct letters arranged in order: 4! = 24.",
    fasterApproach: "nPr with n = r = 4.",
    conceptTested: "Permutation of distinct items.",
    commonTrap: "Multiplying 4×4×4×4 for 256 (repetition) — repetition is disallowed.",
  },
  {
    id: "q-qa-cp-1",
    section: "qa",
    topicId: "qa-mod-counting",
    chapterId: "qa-modern-math",
    difficulty: 1,
    type: "mcq",
    prompt:
      "A menu offers 4 starters, 5 main courses and 3 desserts. How many 3-course dinners can a person order?",
    options: ["12", "48", "60", "64"],
    correctIndex: 2,
    explanation: "4 × 5 × 3 = 60 by the fundamental counting rule.",
    fasterApproach: "Multiply the independent choices.",
    conceptTested: "Fundamental counting principle.",
    commonTrap: "Adding the options (12).",
  },
];

export const VARC_QUESTIONS: Question[] = [
  {
    id: "q-varc-rc-1",
    section: "varc",
    topicId: "varc-rc-main-idea",
    chapterId: "varc-rc",
    difficulty: 2,
    type: "mcq",
    prompt: "Read this mini-passage and choose the main idea:\n\n\"For decades cities treated stormwater as a nuisance to be drained away quickly. But rapid drainage sends pollutants straight into rivers and worsens seasonal floods downstream. Melbourne's 'water-sensitive' redesigns — rain gardens, permeable footpaths and urban wetlands — slow the water, filter it and store it. Early data show cooler streets, revived streams and flood curves that stay flat even in heavy rain.\"",
    options: [
      "Cities have always drained stormwater efficiently.",
      "Water-sensitive urban design can manage rain cities better than rapid drainage.",
      "Melbourne built a new drainage system.",
      "Stormwater contains pollutants.",
    ],
    correctIndex: 1,
    explanation:
      "The passage frames a problem (rapid drainage harms rivers and worsens floods), introduces a solution (water-sensitive design) and gives supporting evidence. That whole arc supports option 2. Options 1 and 4 highlight single details; option 3 is too narrow.",
    fasterApproach: "The contrast 'But rapid drainage…' marks the pivot; the rest supports the new approach.",
    conceptTested: "Main idea and central theme.",
    commonTrap: "Picking a true-but-narrow detail (option 4).",
  },
  {
    id: "q-varc-rc-2",
    section: "varc",
    topicId: "varc-rc-main-idea",
    chapterId: "varc-rc",
    difficulty: 3,
    type: "mcq",
    prompt:
      "\"The invention of the printing press is usually credited with democratising knowledge. The claim needs a careful footnote: for two centuries after Gutenberg, books remained costly and Latin-bound, and the learned elite often read them aloud to illiterate audiences. Print undoubtedly multiplied copies — but the reading revolution that followed was slow, uneven and profoundly social before it became individual.\"\n\nThe central claim of the passage is that:",
    options: [
      "printing presses were expensive to operate",
      "the democratisation of reading after print was gradual and socially mediated",
      "illiterate people copied books",
      "Gutenberg invented the printing press",
    ],
    correctIndex: 1,
    explanation:
      "The passage concedes print's power but qualifies it: the reading revolution was 'slow, uneven and profoundly social'. That qualified claim is the centre. The other options are facts or context, not the argument's spine.",
    conceptTested: "Central claim with qualification.",
    commonTrap: "Stopping at the opening concession rather than the qualified thesis.",
  },
  {
    id: "q-varc-rc-3",
    section: "varc",
    topicId: "varc-rc-inference",
    chapterId: "varc-rc",
    difficulty: 3,
    type: "mcq",
    prompt:
      "\"A longitudinal study followed 4,000 adults for a decade. Those who walked at least 30 minutes daily had a 22% lower risk of cardiovascular events than inactive peers. The researchers stress the association is observational; statin users were included and results held after adjusting for diet, smoking and baseline health.\"\n\nWhich can be inferred from the passage?",
    options: [
      "Walking is proven to cause a 22% reduction in cardiovascular risk.",
      "The protective association with walking persisted after controlling for several confounders.",
      "Statin use eliminated the benefit of walking.",
      "Non-walkers always develop heart disease.",
    ],
    correctIndex: 1,
    explanation:
      "The passage says results 'held after adjusting for diet, smoking and baseline health' — that supports option 2 directly as an inference. Option 1 overstates (observational ≠ causal). Options 3 and 4 contradict or exaggerate the text.",
    conceptTested: "Inference vs overstatement.",
    commonTrap: "Confusing 'association' with causation (option 1).",
  },
  {
    id: "q-varc-va-1",
    section: "varc",
    topicId: "varc-va-para-jumbles",
    chapterId: "varc-va",
    difficulty: 3,
    type: "mcq",
    prompt: "Rearrange these sentences into a coherent paragraph:\n\n1. These swarms — thousands of tiny machines — can coordinate without a leader.\n2. Researchers are now testing drones that move like bird flocks in the wild.\n3. The pattern emerges from simple local rules each drone follows.\n4. For years, however, coordination outside controlled labs proved fragile.",
    options: ["2,1,4,3", "2,4,1,3", "1,2,3,4", "4,2,1,3"],
    correctIndex: 1,
    explanation:
      "Sentence 2 introduces the topic (drones in the wild). Sentence 4 qualifies with the historical fragility, sentence 1 explains what the swarms are ('these swarms' refers back to the drones), and sentence 3 concludes by noting the simple local rules. Order 2,4,1,3 reads cleanly with each pronoun anchored.",
    conceptTested: "Para jumbles — pronoun reference and logical flow.",
    commonTrap: "Leading with 'these swarms' (sentence 1) before anything was introduced.",
  },
  {
    id: "q-varc-va-2",
    section: "varc",
    topicId: "varc-va-para-summary",
    chapterId: "varc-va",
    difficulty: 3,
    type: "mcq",
    prompt:
      "Choose the best summary:\n\n\"Offices designed for open-plan collaboration have spread faster than the evidence for them. Reviews find open plans cut speech privacy, raise distraction complaints and, in several studies, reduce face-to-face interaction rather than raise it. Yet they persist — cheap to build and easy to label progressive.\"",
    options: [
      "Open offices are cheap and popular, so they will keep spreading.",
      "Open-plan offices spread despite mixed evidence, often lowering interaction.",
      "Privacy in offices is less important than collaboration.",
      "Modern office design is a mystery to researchers.",
    ],
    correctIndex: 1,
    explanation:
      "The summary must carry the paradox: spread + weak evidence + reduced interaction. Option 2 captures that tension. Option 1 drops the evidence part; 3 and 4 import new claims or dilute the point.",
    conceptTested: "Para summary with correct emphasis.",
    commonTrap: "Choosing option 1: it is a plausible gloss but drops the key 'evidence' nuance.",
  },
];

export const DILR_QUESTIONS: Question[] = [
  {
    id: "q-dilr-di-table-1",
    section: "dilr",
    topicId: "dilr-di-tables",
    chapterId: "dilr-di",
    difficulty: 2,
    type: "mcq",
    prompt:
      "A company's quarterly sales (in ₹ lakh): Q1 120, Q2 150, Q3 130, Q4 200. What percentage of the yearly total did Q4 contribute?",
    options: ["30.5%", "33.33%", "36.36%", "25%"],
    correctIndex: 1,
    explanation: "Total = 120+150+130+200 = 600. Q4 share = 200/600 = 33.33%.",
    fasterApproach: "200 out of 600 → 1/3 → 33.33%.",
    conceptTested: "Percentage share from a table.",
    commonTrap: "Percentaging Q4 against four quarters (25%).",
  },
  {
    id: "q-dilr-lr-scale",
    section: "dilr",
    topicId: "dilr-lr-linear",
    chapterId: "dilr-lr",
    difficulty: 3,
    type: "mcq",
    prompt:
      "Six students A, B, C, D, E and F sit in a row facing north. C is at one extreme end. A is immediately to the left of B. D sits between A and E. E sits immediately to the left of D. F sits at the first position from the left. What is the position of A counting from the left?",
    options: ["2", "3", "4", "5"],
    correctIndex: 2,
    explanation:
      "F is at position 1, so C must be at position 6 (the other extreme). E is immediately left of D, so E,D are an adjacent block with E before D. Since D sits between A and E, and E is already to the left of D, A must lie to the right of D. So we get the adjacent run E, D, A. Now A is immediately left of B, so B follows A: the run becomes E, D, A, B occupying positions 2–5. Hence A is at position 4.",
    fasterApproach: "Build the forced blocks: (E,D) and (A,B), glued as E-D-A-B by the 'between' condition.",
    conceptTested: "Linear arrangement with forced adjacency blocks.",
    commonTrap: "Assuming 'D between A and E' means A on the left without checking the E-left-of-D clause.",
  },
];

export const QUESTION_BANK: Question[] = [
  ...QA_QUESTIONS,
  ...VARC_QUESTIONS,
  ...DILR_QUESTIONS,
];