import { makeChapter } from "./helpers";
import type { Chapter } from "../types";

const readingComprehension = makeChapter("varc-rc", "varc", "Reading Comprehension", 1, [
  {
    id: "varc-rc-main-idea",
    title: "Main Idea & Central Theme",
    description: "The single claim a passage is built around.",
    difficulty: 1,
    priority: 1,
    estimatedMinutes: 35,
    concept:
      "Every coherent passage argues or explains one central thing. The main idea is that claim, stated broadly. The title question and the author's central theme question both point to it. Read to accumulate a one-sentence 'what is this really about?' answer while reading. The correct option is the one that covers the entire passage — a common wrong option covers only one paragraph.",
    coreRules: [
      "The main idea must cover the WHOLE passage, not one paragraph.",
      "If an option is too specific, it describes a detail, not the main idea.",
      "Ask: 'What would the title be?' — a good main-idea option doubles as a title.",
    ],
    formulas: [],
    examples: [
      {
        title: "Distinguishing detail from theme",
        level: "Moderate",
        question: "A passage discusses several studies of sleep and ends by noting sleep consolidates memory. Which is the main idea?",
        solution: [
          "The studies are evidence; the claim 'sleep consolidates memory' organizes them.",
          "Options mentioning only one study are detail-level answers.",
          "Answer: sleep consolidates memory.",
        ],
      },
    ],
    commonMistakes: ["Picking an option that is true but too narrow.", "Picking an option that is broader than the passage."],
    shortcuts: ["Read the first and last sentences of every paragraph as you scan — they usually trace the argument."],
    videoId: "varc-video-rc",
    practiceQuestionIds: ["q-varc-rc-1", "q-varc-rc-2"],
  },
  {
    id: "varc-rc-tone",
    title: "Author's Tone & Purpose",
    description: "Recognizing the author's attitude and reason for writing.",
    difficulty: 2,
    priority: 1,
    estimatedMinutes: 35,
    prerequisites: ["varc-rc-main-idea"],
    concept:
      "Tone is the author's attitude — objective, skeptical, admiring, ironic, alarmist. Purpose is why the passage exists: to explain, critique, defend, call to action. Clue words ('sadly', 'importantly', 'supposedly') flag attitude. An objective tone uses neutral reporting; a persuaded tone uses value-laden words.",
    coreRules: [
      "Value-laden adjectives signal attitude.",
      "Scare-quoted or 'allegedly' words signal skepticism.",
      "Purpose options use verbs: 'to propose', 'to critique', 'to illustrate'.",
    ],
    formulas: [],
    examples: [
      {
        title: "Tone recognition",
        level: "Easy",
        question: "A text: 'The scheme, supposedly progressive, quietly stripped benefits from the poorest.' Tone?",
        solution: ["'Supposedly' and 'quietly stripped' signal distrust.", "Answer: skeptical/critical."],
      },
    ],
    commonMistakes: ["Calling every critical passage 'sarcastic'.", "Confusing tone with the subject matter's difficulty."],
    shortcuts: [],
    videoId: "varc-video-rc",
    practiceQuestionIds: [],
  },
  {
    id: "varc-rc-inference",
    title: "Inference",
    description: "Conclusions that follow from the passage but aren't stated.",
    difficulty: 3,
    priority: 1,
    estimatedMinutes: 40,
    prerequisites: ["varc-rc-main-idea"],
    concept:
      "An inference is a claim the passage supports without saying. The wrong trap is 'beyond the scope' (reasonable-sounding but unsupported) and 'paraphrase' (restates the text rather than going beyond it). Ask: 'If this passage is true, must this also be true?' — that 'must' is the standard.",
    coreRules: [
      "A valid inference is guaranteed (or strongly indicated), not merely plausible.",
      "Restating the text is not inferring.",
      "Test options with: 'Would the author agree?'",
    ],
    formulas: [],
    examples: [
      {
        title: "Supported vs plausible",
        level: "Moderate",
        question: "Passage: only 3% of managed forests burned, while 27% of unmanaged ones did. What can be inferred?",
        solution: [
          "Plausible-but-unsupported: 'all forests will burn eventually.'",
          "Supported: 'managed forests were more resilient to fire in this study.'",
          "Answer: the supported, hedged claim.",
        ],
      },
    ],
    commonMistakes: ["Picking tempting beyond-the-scope options.", "Picking pure paraphrase options."],
    shortcuts: ["Prefer the most hedged option among supported-sounding answers."],
    videoId: "varc-video-rc",
    practiceQuestionIds: ["q-varc-rc-3"],
  },
  {
    id: "varc-rc-fact-inference",
    title: "Fact vs Inference",
    description: "Separating stated facts from derived conclusions.",
    difficulty: 2,
    priority: 2,
    estimatedMinutes: 30,
    prerequisites: ["varc-rc-inference"],
    concept:
      "A fact is explicitly stated or directly observable from the data in the passage. An inference goes one logical step beyond. The question asks you to identify which option is (or is not) a fact — verify each option against the letter of the text before choosing.",
    coreRules: ["Facts can be pointed to in the text; inferences cannot.", "'May', 'likely', 'probably' usually mark inferences in options."],
    formulas: [],
    examples: [
      {
        title: "Classify options",
        level: "Beginner",
        question: "Given 'sales rose 12% in Q3'. Which is a fact/inference pair?",
        solution: ["Fact: 'sales rose 12% in Q3'.", "Inference: 'the company will beat targets next quarter.'", "Answer: as classified."],
      },
    ],
    commonMistakes: [],
    shortcuts: ["Scan for statistic-verbatim phrasing to spot facts."],
    videoId: "varc-video-rc",
    practiceQuestionIds: [],
  },
  {
    id: "varc-rc-strong-weak",
    title: "Strong and Weak Arguments",
    description: "Evaluating argument support and relevance.",
    difficulty: 3,
    priority: 2,
    estimatedMinutes: 35,
    prerequisites: ["varc-rc-inference"],
    concept:
      "An argument = evidence + conclusion. A strong argument's evidence is relevant, recent, representative and sufficient; a weak one fails on one of those. CAT asks which statement strengthens/weakens a conclusion, or whether an argument is well supported. The test: does the option actually move the conclusion — up or down?",
    coreRules: [
      "An option that doesn't touch the conclusion is irrelevant, however true.",
      "To weaken: attack relevance, sufficiency, or introduce counter-evidence.",
      "To strengthen: add representative supporting evidence.",
    ],
    formulas: [],
    examples: [
      {
        title: "Weakening",
        level: "Moderate",
        question: "Conclusion: 'Exercise reduces depression.' Which weakens it?",
        solution: [
          "Irrelevant: 'exercise has other benefits.'",
          "Weakening: 'depressed subjects in the study also received therapy.'",
          "Answer: the confounder option.",
        ],
      },
    ],
    commonMistakes: ["Choosing 'true but irrelevant' options."],
    shortcuts: [],
    videoId: "varc-video-rc",
    practiceQuestionIds: [],
  },
  {
    id: "varc-rc-paragraph-function",
    title: "Paragraph Function & Passage Structure",
    description: "Why each paragraph exists in the whole.",
    difficulty: 3,
    priority: 2,
    estimatedMinutes: 35,
    prerequisites: ["varc-rc-main-idea"],
    concept:
      "Each paragraph usually plays one role: introduce the problem, give evidence, consider an objection, qualify the claim, conclude. Function questions ask 'what does paragraph X do?' Track the movement of the argument as you read — noting keywords like 'however', 'for instance', 'some argue that' — so the structure is visible when you reach the question.",
    coreRules: [
      "'However' and 'but' introduce a turn or objection.",
      "'For example' signals illustration; 'therefore' signals conclusion.",
      "A paragraph can do two jobs — pick the option naming the primary one.",
    ],
    formulas: [],
    examples: [
      {
        title: "Function spotting",
        level: "Easy",
        question: "A paragraph begins 'Critics contend that the model ignores history…' What is its function?",
        solution: ["The phrase signals presenting an objection.", "Answer: presents a counterargument."],
      },
    ],
    commonMistakes: ["Describing content instead of function."],
    shortcuts: [],
    videoId: "varc-video-rc",
    practiceQuestionIds: [],
  },
  {
    id: "varc-rc-vocabulary",
    title: "Vocabulary in Context",
    description: "Meaning from context — the word matters less than the sentence.",
    difficulty: 2,
    priority: 1,
    estimatedMinutes: 30,
    prerequisites: ["varc-rc-main-idea"],
    concept:
      "Vocabulary-in-context questions rarely test dictionary meanings alone. Read the sentence around the word, decide what idea fits, then match the option. Wrong options are usually the word's other dictionary sense. Look for contrast clues ('but', 'although') and parallel clues ('and', 'similarly') in nearby clauses.",
    coreRules: ["Find the sentence's own definition before choosing.", "Answer must fit, not merely be a synonym in isolation.", "Contrast words flip expected meaning."],
    formulas: [],
    examples: [
      {
        title: "Context over dictionary",
        level: "Beginner",
        question: "'The austere campus forbade posters and strumming.' 'Austere' here means?",
        solution: ["The examples (no posters, no music) show strictness.", "Answer: severely simple/strict.", "The 'stern' synonym family wins over 'wealthy' senses."],
      },
    ],
    commonMistakes: ["Choosing an irrelevant dictionary sense."],
    shortcuts: ["Substitute each option in place — the one that reads naturally wins."],
    videoId: "varc-video-rc",
    practiceQuestionIds: [],
  },
  {
    id: "varc-rc-elimination",
    title: "Elimination Techniques",
    description: "Systematic option-weeding for RC questions.",
    difficulty: 2,
    priority: 1,
    estimatedMinutes: 30,
    prerequisites: ["varc-rc-main-idea"],
    concept:
      "Elimination is the RC-solver's primary weapon. Kill options that: (1) are beyond scope, (2) contradict the text, (3) distort by using 'all'/'never' too absolutely, (4) quote the passage but mean something different (word-bait). A systematic killer list beats rereading the passage for every question.",
    coreRules: [
      "Skip-first, attack-answer: eliminate wrong ones to isolate the survivor.",
      "Extreme qualifiers ('always', 'only', 'never') are usually wrong unless the passage is equally absolute.",
      "Options that copy passage words often distort the import.",
    ],
    formulas: [],
    examples: [
      {
        title: "Word-bait trap",
        level: "Moderate",
        question: "Passage says 'some economists doubt X'. Option: 'Most economists doubt X'. Why wrong?",
        solution: ["'Some' ≠ 'most' — a quantifier distortion.", "Answer: the option overstates the passage claim."],
      },
    ],
    commonMistakes: ["Falling for exact-word options with shifted meaning."],
    shortcuts: ["Read options BEFORE rereading the passage; you'll know what to look for."],
    videoId: "varc-video-rc",
    practiceQuestionIds: [],
  },
  {
    id: "varc-rc-critical-reasoning",
    title: "Critical Reasoning",
    description: "Argument evaluation: assumptions, strengthen, weaken, flaw.",
    difficulty: 3,
    priority: 2,
    estimatedMinutes: 40,
    prerequisites: ["varc-rc-strong-weak"],
    concept:
      "Critical reasoning isolates an argument and asks one of: find the assumption, strengthen, weaken, identify the flaw, draw the conclusion. The assumption is what the argument silently needs to be true. Fix the conclusion first, then test each option as 'what must the author believe?'",
    coreRules: [
      "Assumption test: negate the option; if the argument collapses, it's the assumption.",
      "A flaw answer describes a logical misstep, not a factual error.",
      "Strengthen/weaken options must change the support for the conclusion.",
    ],
    formulas: [],
    examples: [
      {
        title: "Assumption",
        level: "Moderate",
        question: "Sales rose after the ad campaign; the company concludes the ads worked. Assumption?",
        solution: [
          "The argument needs: sales would not have risen anyway.",
          "Negation kills the conclusion, confirming it.",
          "Answer: sales were not rising from other causes.",
        ],
      },
    ],
    commonMistakes: ["Selecting correlated-but-irrelevant facts."],
    shortcuts: ["The negation test settles most assumption questions instantly."],
    videoId: "varc-video-rc",
    practiceQuestionIds: [],
  },
]);

const verbalAbility = makeChapter("varc-va", "varc", "Verbal Ability", 2, [
  {
    id: "varc-va-para-jumbles",
    title: "Para Jumbles",
    description: "Reordering sentences into a logical paragraph.",
    difficulty: 3,
    priority: 1,
    estimatedMinutes: 40,
    prerequisites: ["varc-rc-paragraph-function"],
    concept:
      "Para jumbles present shuffled sentences; reconstruct the paragraph. Tools: (1) anchor sentences — introductions often name a topic generally, (2) pronoun links ('they' must follow its noun), (3) time/sequence markers, (4) logical connectors ('therefore', 'however'). First and last sentences are usually the easiest to fix; chain from there.",
    coreRules: [
      "Pronouns ('it', 'this', 'they') force their referent earlier.",
      "'The' appears after a thing is introduced; 'a' often introduces.",
      "Time markers order the narrative; contrast markers flip direction.",
    ],
    formulas: [],
    examples: [
      {
        title: "Pronoun chaining",
        level: "Moderate",
        question: "Sentences: (1) The robots scan shelves (2) They then restock (3) Grocery stores are adopting them. Best order?",
        solution: [
          "(3) introduces the stores adopting 'them'.",
          "(1) says what the robots do; (2) continues with 'they'.",
          "Answer: 3,1,2.",
        ],
      },
    ],
    commonMistakes: ["Forcing a chain that breaks pronoun references."],
    shortcuts: ["Fix the two most obvious links first, then place leftovers."],
    videoId: "varc-video-va",
    practiceQuestionIds: ["q-varc-va-1"],
  },
  {
    id: "varc-va-para-summary",
    title: "Para Summary",
    description: "Compressing a paragraph into one best sentence.",
    difficulty: 3,
    priority: 1,
    estimatedMinutes: 40,
    prerequisites: ["varc-rc-main-idea"],
    concept:
      "A summary must capture the argument's spine: the claim plus the key reasons, in correct emphasis. Wrong options: (1) too broad, (2) focused on a supporting example, (3) adding ideas the paragraph lacks, (4) pluralizing ('studies' when one study). Draft your own summary first, then match.",
    coreRules: [
      "Preserve the emphasis — the main claim must be the main clause.",
      "Details belong only if they change the meaning.",
      "Reject options with new claims not in the paragraph.",
    ],
    formulas: [],
    examples: [
      {
        title: "Emphasis check",
        level: "Moderate",
        question: "Paragraph claims remote work helps focus but hurts mentoring. Which summary?",
        solution: [
          "Best: 'Remote work trades mentorship for focus.'",
          "Wrong: 'Remote work is great for companies' (adds an unsupported value claim).",
        ],
      },
    ],
    commonMistakes: ["Choosing an option that sounds good but shifts the claim."],
    shortcuts: ["State the claim and reason in your head before reading options."],
    videoId: "varc-video-va",
    practiceQuestionIds: [],
  },
  {
    id: "varc-va-odd-sentence",
    title: "Odd Sentence",
    description: "Finding the sentence that breaks thematic coherence.",
    difficulty: 3,
    priority: 2,
    estimatedMinutes: 35,
    prerequisites: ["varc-va-para-jumbles"],
    concept:
      "Four or five sentences share a theme; one is off-topic, wrongly toned, or attached to a different subject. Read the group for the common thread first, then flag the sentence whose subject, timeline or register breaks it. The odd one often sounds inflected or adds an unrelated example.",
    coreRules: ["Identify the thread (subject + claim) before judging.", "Register and tense shifts can make a sentence odd.", "The odd sentence may be grammatically fine — coherence is the test."],
    formulas: [],
    examples: [
      {
        title: "Theme break",
        level: "Easy",
        question: "Sentences about monsoon forecasting; one sentence describes wheat export policy. Which stands out?",
        solution: ["The others share 'monsoon forecasting'.", "Answer: the wheat-policy sentence."],
      },
    ],
    commonMistakes: ["Choosing a slightly-edited true sentence."],
    shortcuts: [],
    videoId: "varc-video-va",
    practiceQuestionIds: [],
  },
  {
    id: "varc-va-sentence-completion",
    title: "Sentence Completion",
    description: "Choosing words that fit meaning and register.",
    difficulty: 2,
    priority: 2,
    estimatedMinutes: 35,
    concept:
      "Completion questions supply a stripped sentence; the best option restores meaning and style. Signal words within the sentence decide whether the blank continues or contradicts the preceding idea. Eliminate by fit (that which breaks the logic) before style.",
    coreRules: ["Read the full sentence for the signpost ('but', 'so').", "The correct word honors tone and register, not just the dictionary."],
    formulas: [],
    examples: [
      {
        title: "Contrast signpost",
        level: "Easy",
        question: "The proposal was greeted with enthusiasm by some and ____ by others.",
        solution: ["'But'-style contrast needs a negative reaction.", "Answer: skepticism."],
      },
    ],
    commonMistakes: ["Choosing a synonym that ignores the signpost."],
    shortcuts: [],
    videoId: "varc-video-va",
    practiceQuestionIds: [],
  },
  {
    id: "varc-va-paragraph-completion",
    title: "Paragraph Completion",
    description: "Finishing a paragraph with the correct concluding thought.",
    difficulty: 3,
    priority: 1,
    estimatedMinutes: 35,
    prerequisites: ["varc-va-para-summary"],
    concept:
      "The final sentence must follow from everything before it — extending, concluding or qualifying. Options that restate the first sentence fail (the paragraph already moved on); options introducing brand-new claims also fail. The right answer sounds like the paragraph's natural last breath.",
    coreRules: ["The ending continues the paragraph's momentum — no new topics.", "It may conclude, or leave a deliberate open question.", "Test by deletion: fit each option and hear which ends cleanly."],
    formulas: [],
    examples: [
      {
        title: "Natural ending",
        level: "Moderate",
        question: "A paragraph traces a company's struggles and changing strategy. Best concluding line?",
        solution: [
          "Restating the opening fails (no momentum).",
          "Best: a line synthesizing 'the strategy marked both risk and possibility.'",
        ],
      },
    ],
    commonMistakes: ["Ending on a strong claim the paragraph never supported."],
    shortcuts: [],
    videoId: "varc-video-va",
    practiceQuestionIds: [],
  },
  {
    id: "varc-va-sentence-arrangement",
    title: "Sentence Arrangement & Logical Flow",
    description: "Ordering sentences by cause, evidence and time.",
    difficulty: 3,
    priority: 1,
    estimatedMinutes: 35,
    prerequisites: ["varc-va-para-jumbles"],
    concept:
      "Arrangement questions give a handful of sentences and ask for the sequence that reads as a connected flow. Look for: referents of pronouns, causal pairs ('because of that'), examples following claims, and chronological markers. Its logic mirrors para jumbles with stricter time/argument linkage.",
    coreRules: ["Chronology or causal chain dominates the order.", "Claim before example; problem before solution.", "Pronoun/antecedent pairs are the strongest anchors."],
    formulas: [],
    examples: [
      {
        title: "Causal chain",
        level: "Easy",
        question: "Sentences: demand fell; factories idled; layoffs followed. Correct order?",
        solution: ["Demand fell → factories idled → layoffs.", "Answer: that causal chain."],
      },
    ],
    commonMistakes: ["Rearranging by 'sounds nice' instead of by links."],
    shortcuts: [],
    videoId: "varc-video-va",
    practiceQuestionIds: [],
  },
  {
    id: "varc-va-grammar",
    title: "Grammar for CAT",
    description: "Subject–verb agreement, tense, parallelism and modifiers.",
    difficulty: 2,
    priority: 2,
    estimatedMinutes: 40,
    concept:
      "CAT grammar is error-spotting and sentence-correction. The recurring fault lines: agreement (subject and verb), tense sequence, modifier placement (dangling participles), parallel list structure, and pronoun case. Read sentences aloud — most errors are audible — then check the top four patterns.",
    coreRules: [
      "Match subject and verb despite interferences ('one of the players who were…').",
      "Keep lists parallel (noun, noun, noun).",
      "A participle must agree with its implied subject.",
    ],
    formulas: [],
    examples: [
      {
        title: "Agreement",
        level: "Easy",
        question: "'The group of students are…' or 'is…'?",
        solution: ["'Group' is singular (collective noun) acting as subject.", "Answer: 'is'."],
      },
    ],
    commonMistakes: ["Agreeing with a noun that isn't the subject."],
    shortcuts: ["Delete the middle phrases to reveal the subject and verb."],
    videoId: "varc-video-va",
    practiceQuestionIds: [],
  },
]);

import type { Chapter as VChapter } from "../types";
export const VARC_CHAPTERS: VChapter[] = [readingComprehension, verbalAbility];