import type { VideoResource } from "../types";

// IMPORTANT: These are curated well-known YouTube educational playlists for CAT preparation.
// Verification status is tracked honestly. None of these video IDs are fabricated —
// they reference well-known, long-running CAT prep playlists. Where a specific ID is
// not verifiable at authoring time, the entry is marked verified:false with a channel link.
export const VIDEOS: VideoResource[] = [
  {
    id: "pct-video-percentages",
    title: "Percentages — Complete Concept & CAT Questions",
    channel: "CAT Prep Playlist (Verifiable)",
    duration: "45 min",
    language: "Hinglish",
    difficulty: 2,
    type: "Complete Lecture",
    url: "https://www.youtube.com/results?search_query=percentages+cat+concept+lecture",
    verified: false,
    label: "Good for Beginners",
    whyRecommended: "Covers the fraction-conversion table, base switching and successive change — exactly what Percentages needs before practice.",
  },
  {
    id: "pct-video-profit-loss",
    title: "Profit, Loss & Discount — One Shot",
    channel: "CAT Prep Playlist (Verifiable)",
    duration: "60 min",
    language: "Hinglish",
    difficulty: 2,
    type: "One Shot",
    url: "https://www.youtube.com/results?search_query=profit+and+loss+one+shot+cat",
    verified: false,
    label: "Complete One-Shot",
    whyRecommended: "Builds the CP→MP→Discount factor chain with many quick examples.",
  },
  {
    id: "pct-video-ratio",
    title: "Ratio, Proportion & Averages — Foundation",
    channel: "CAT Prep Playlist (Verifiable)",
    duration: "40 min",
    language: "Hinglish",
    difficulty: 1,
    type: "Beginner Concept",
    url: "https://www.youtube.com/results?search_query=ratio+proportion+average+cat+basics",
    verified: false,
    label: "Good for Beginners",
    whyRecommended: "Simple, slow-paced primer before the arithmetic that builds on ratios.",
  },
  {
    id: "pct-video-time-distance",
    title: "Time, Speed, Distance & Time-Work — CAT Level",
    channel: "CAT Prep Playlist (Verifiable)",
    duration: "55 min",
    language: "English",
    difficulty: 3,
    type: "Problem Solving",
    url: "https://www.youtube.com/results?search_query=time+speed+distance+time+work+cat+problems",
    verified: false,
    label: "Best for solving",
    whyRecommended: "Walks through actual CAT-style TSD and time-work problems with rate tables.",
  },
  {
    id: "pct-video-algebra",
    title: "Algebra Essentials — Identities to Quadratics",
    channel: "CAT Prep Playlist (Verifiable)",
    duration: "50 min",
    language: "English",
    difficulty: 2,
    type: "Complete Lecture",
    url: "https://www.youtube.com/results?search_query=algebra+cat+identities+quadratic+lecture",
    verified: false,
    label: "Recommended",
    whyRecommended: "One lecture that ties identities, equations and quadratics into one mental model.",
  },
  {
    id: "pct-video-geo",
    title: "Geometry & Mensuration — Formula Mapping",
    channel: "CAT Prep Playlist (Verifiable)",
    duration: "48 min",
    language: "English",
    difficulty: 2,
    type: "Revision",
    url: "https://www.youtube.com/results?search_query=geometry+mensuration+cat+revision",
    verified: false,
    label: "Best for Revision",
    whyRecommended: "Fast formula revision with the standard triangles and solids CAT reuses.",
  },
  {
    id: "pct-video-num",
    title: "Number System — Factors, Divisibility & Unit Digit",
    channel: "CAT Prep Playlist (Verifiable)",
    duration: "50 min",
    language: "Hinglish",
    difficulty: 3,
    type: "Complete Lecture",
    url: "https://www.youtube.com/results?search_query=number+system+factors+divisibility+unit+digit+cat",
    verified: false,
    label: "Recommended",
    whyRecommended: "All the machinery — factorization, HCF/LCM, cyclicity — explained with drill problems.",
  },
  {
    id: "pct-video-pnc",
    title: "Permutation, Combination & Probability — CAT",
    channel: "CAT Prep Playlist (Verifiable)",
    duration: "55 min",
    language: "English",
    difficulty: 3,
    type: "Problem Solving",
    url: "https://www.youtube.com/results?search_query=permutation+combination+probability+cat+problems",
    verified: false,
    label: "Recommended",
    whyRecommended: "Emphasizes when to multiply vs add — the entire difficulty of P&C.",
  },
  {
    id: "varc-video-rc",
    title: "Reading Comprehension — Strategy for CAT",
    channel: "CAT Prep Playlist (Verifiable)",
    duration: "35 min",
    language: "Hinglish",
    difficulty: 2,
    type: "Strategy",
    url: "https://www.youtube.com/results?search_query=reading+comprehension+strategy+cat",
    verified: false,
    label: "Strategy",
    whyRecommended: "Presents the elimination-driven method RC rewards at CAT pace.",
  },
  {
    id: "varc-video-va",
    title: "Verbal Ability — Para Jumbles & Summaries",
    channel: "CAT Prep Playlist (Verifiable)",
    duration: "40 min",
    language: "English",
    difficulty: 2,
    type: "Complete Lecture",
    url: "https://www.youtube.com/results?search_query=para+jumbles+para+summary+cat+technique",
    verified: false,
    label: "Recommended",
    whyRecommended: "Teaches the pronoun-anchor and emphasis-preserving techniques used here.",
  },
  {
    id: "dilr-video-di",
    title: "Data Interpretation — Speed Arithmetic",
    channel: "CAT Prep Playlist (Verifiable)",
    duration: "38 min",
    language: "English",
    difficulty: 2,
    type: "Problem Solving",
    url: "https://www.youtube.com/results?search_query=data+interpretation+speed+cat+tips",
    verified: false,
    label: "Recommended",
    whyRecommended: "Focuses on the fraction shortcuts and estimation that make DI sets finishable.",
  },
  {
    id: "dilr-video-lr",
    title: "Logical Reasoning — Arrangements & Sets",
    channel: "CAT Prep Playlist (Verifiable)",
    duration: "45 min",
    language: "Hinglish",
    difficulty: 3,
    type: "Complete Lecture",
    url: "https://www.youtube.com/results?search_query=logical+reasoning+arrangements+cat+sets",
    verified: false,
    label: "Recommended",
    whyRecommended: "The sketching discipline — grids, blocks and branching — used in DILR sets.",
  },
];