import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const dir = join(process.cwd(), "scripts", "tmp");

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

function fmtMs(ms) {
  const m = Math.round(Number(ms) / 60000);
  if (!m) return "";
  const h = Math.floor(m / 60);
  const r = m % 60;
  if (h === 0) return `${r}m`;
  return `${h}h ${r}m`;
}

async function fetchDuration(id) {
  try {
    const res = await fetch(`https://www.youtube.com/watch?v=${id}`, {
      headers: { "user-agent": "Mozilla/5.0", "accept-language": "en" },
      signal: AbortSignal.timeout(9000),
    });
    const html = await res.text();
    const m = html.match(/"approxDurationMs":"(\d+)"/);
    return m ? fmtMs(m[1]) : "";
  } catch {
    return "";
  }
}

function esc(s) {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

async function buildVideos() {
  const verified = JSON.parse(readFileSync(join(dir, "verified-videos.json"), "utf8"));
  verified.sort((a, b) => (a.topicId < b.topicId ? -1 : 1));

  const lines = [];
  for (let i = 0; i < verified.length; i++) {
    const v = verified[i];
    if ((i % 40) === 39) {
      process.stdout.write(`durations ${i + 1}/${verified.length}\n`);
      await sleep(200);
    }
    let duration = v.duration || "";
    if (!duration) {
      const d = await fetchDuration(v.youtubeId);
      if (d) duration = d;
    }
    const chapterId = v.topicId.split("-").slice(0, 2).join("-");
    lines.push(`  {
    id: "${v.topicId}-video",
    topicId: "${v.topicId}",
    chapterId: "${chapterId}",
    title: "${esc(v.title)}",
    channel: "${esc(v.channel)}",
    duration: "${duration || "—"}",
    language: "${esc(v.language)}",
    difficulty: ${v.difficulty},
    type: "${esc(v.type)}",
    youtubeId: "${v.youtubeId}",
    url: "https://www.youtube.com/watch?v=${v.youtubeId}",
    verified: true,
    whyRecommended: "${esc(v.note)}",
  },`);
  }

  const out = `import type { VideoResource } from "../types";

// Generated by scripts/build-content.mjs from scripts/tmp/verified-videos.json.
// Every entry was verified live via the YouTube oEmbed API (real title + channel),
// so youtubeId is guaranteed to resolve. Durations are read from the watch page
// where retrievable, otherwise shown as "—".
export const VIDEOS: VideoResource[] = [
${lines.join("\n")}
];
`;
  writeFileSync(join(process.cwd(), "src", "lib", "content", "videos.ts"), out);
  console.log(`videos.ts written with ${verified.length} entries`);
}

function buildPapers() {
  const verified = JSON.parse(readFileSync(join(dir, "verified-papers.json"), "utf8"));
  const years = ["2024", "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "multi"];
  verified.sort((a, b) => years.indexOf(a.year) - years.indexOf(b.year));

  const lines = verified.map(
    (p, i) => `  {
    id: "paper-${i + 1}",
    name: "${p.title.replace(/"/g, '\\"')}",
    type: "pdf",
    category: "Past Paper",
    source: "Verified public PDF link",
    url: "${p.url}",
    free: true,
    verified: true,
    note: "${p.year === "multi" ? "Compilation across years." : `CAT ${p.year} question paper — verified live, served as application/pdf.`}",
  },`
  );

  const out = `import type { ResourceEntry } from "../types";

// Generated by scripts/build-content.mjs from scripts/tmp/verified-papers.json.
// Every URL returned HTTP 200 with an application/pdf response (checked live).
export const CAT_PAST_PAPERS: ResourceEntry[] = [
${lines.join("\n")}
];
`;
  writeFileSync(join(process.cwd(), "src", "lib", "content", "papers.ts"), out);
  console.log(`papers.ts written with ${verified.length} entries`);
}

buildPapers();
buildVideos().catch((e) => {
  console.error(e);
  process.exit(1);
});